### ISSUE TITLE
CPU usage while idle

### ISSUE THREAD

**Issue by Joe-Klauza** [benotter/TurnSignal#15]
Continuing the discussion from https://github.com/benotter/TurnSignal/issues/12#issuecomment-318920578, CPU usage while SteamVR is not active seems to be about 1-2% while idle, higher than other idle applications. A sleep could be added between checks of the SteamVR process to reduce this.

While SteamVR is running, roughly 2-3% of the CPU is used, though I'm not sure this can be helped without affecting the accuracy of the application.

OS: Windows 10
Processor: i7-6700K
RAM: 16 GB
GPU: EVGA 1080 Ti Hybrid
Tested release: [2.1.2](https://github.com/benotter/TurnSignal/tree/2.1.2)

**Comment by benotter** [comment]
(Hopefully) Fixed with #17 ! 
Please download latest release (2.1.5), and let me know if that works!
