### ISSUE TITLE
Get TurnSignal On Steam!

### ISSUE THREAD

**Issue by benotter** [benotter/TurnSignal#18]
I think TurnSignal deserves to be on Steam with all the reception its gotten, I'd hate to have a fractured user-base where people might not get the news on updates, and as a result, not get latest features / performance fixes! 

I would hate to have someone not getting the best experience they could with anything I made, otherwise what is the point?

Of course, TurnSignal will always stay free, and will never be sold!

**Comment by benotter** [comment]
Aaaaaand, whamo, bamo!

Going live tonight!

**Comment by darklordabc** [comment]
Bravo!
