### ISSUE TITLE
Inaccurate twisting measurements while playing Echo Arena (via Revive)

### ISSUE THREAD

**Issue by Kipmo** [benotter/TurnSignal#21]
After a few games of Echo Arena and untwisting myself according to TurnSignal in between goals, I'll often find that my headset is twisted in one direction many times. I have noticed that the TurnSignal will reset itself to zero sometimes without me hitting the reset button and it has happened a couple of times where I'll untwist myself to zero and enter a new game and look down to see that TurnSignal is saying that I'm fairly twisted in one direction. If I use the turn indicator in SteamVR Advanced Settings, it is always 100% accurate.

**Comment by benotter** [comment]
Will look into replicating, and improving math for turn detection,

Is there anything particular about Echo Arena that makes its turning, abnormal in any sense? Like, looking very high up or down, or something odd like that?

I suspect that both my jump correction algorithm, and having the headset pointed up or down, but I need a bit more use information from users in the field.

**Comment by Kipmo** [comment]
I think its a pretty typical game in terms of turning. Is there any way for
you to read the current rotation from the same source as SteamVR Advanced
Settings? Like I mentioned, that's always accurate. And simply reading that
value would eliminate a lot of a calculation that TurnSignal is doing.

**Comment by benotter** [comment]
Still unable to reproduce, but I will still work on finding a better way to track rotations, 
I did end up messaging the OpenVR dev, who gave some good info on the topic, so next update I'll do my best to incorporate some accuracy!
