### ISSUE TITLE
"Hide Window" makes TurnSignal sluggish

### ISSUE THREAD

**Issue by Allon-Guralnek** [benotter/TurnSignal#3]
I just enabled "Hide Window" for the first time, and while it in fact hid the window, I noticed the update rate of the TurnSignal texture went down to somewhere around 5 FPS (while SteamVR Home kept running at the normal smooth 90 FPS). The first time I turned it on, the "Missing Frames" warning appeared (that was the first time I ever saw it, but I've only had my Vive for a few weeks), but it disappeared after a few seconds.  Now whenever the checkbox for "Hide Window" is checked, the update rate of TurnSignal is very low, and when I uncheck it, it immediatly returns to being nice and smooth. I think Windows might be deprioritizing threads of applications that have their main window hidden.

I'm using Windows 10 x64 (1703, creators update) with SteamVR Beta on a i7-7700K 16 GB RAM with a GTX1080.

**Comment by benotter** [comment]
Strange! Thanks for the heads up, I had not done perf testing on hidden windowed mode, but I will get to it.

I've actually thought of a better way to optimize, by limiting re-renders to only on info-changes; Like when the mouse moves over something, or when the twist value has changed past a certain point. It currently renders at a fixed rate for the floor, and only renders out the menu when its open tho.

**Comment by benotter** [comment]
Option to hide window removed in version 2.0, in lieu of automatic window minimizing and auto starting / closing with SteamVR! #9
