### ISSUE TITLE
[Bug] Memory leak somewhere, not sure where though.

### ISSUE THREAD

**Issue by GroxicTinch** [benotter/TurnSignal#5]
Every second the memory usage increased by about 430kb, I was playing Recroom for an hour or so and the memory usage atm is 328mb.

**Comment by benotter** [comment]
Heya, thanks for the report!  
A mem-leak, huh? Well, That's what I get for getting comfy with JavaScript! 
I probably have a copied struct getting referenced while being passed or something, I'll poke around and see if I can find it!

**Comment by benotter** [comment]
(Hopefully) Fixed in 2.0! #9
